"""
LoRA Generator — Training Script

Losses
------
1. Weight MSE  : MSE between generated LoRA weights and ground-truth B-LoRA weights
2. CLIP Image  : MSE between CLIP embeddings of:
                    - image generated by SDXL + generated LoRA (differentiable single-step)
                    - image generated by SDXL + gt B-LoRA        (no_grad single-step)

Usage
-----
python -m lora_generator.train \
    --checkpoint_dir /scratch/ohitit20/checkpoints/blora_universal_style_token \
    --image_dir      /home/ohitit20/ip-lora/ref_images/style \
    --output_dir     /scratch/ohitit20/checkpoints/lora_generator \
    --epochs 100 --lr 1e-4 --lambda_clip 1.0 --wandb
"""

from __future__ import annotations

import argparse
import os
import sys
from contextlib import contextmanager
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
from diffusers import AutoencoderKL, DPMSolverMultistepScheduler, StableDiffusionXLPipeline
from diffusers.loaders import LoraLoaderMixin
from torch.utils.data import DataLoader
from torchvision.utils import save_image
from transformers import CLIPVisionModel
from tqdm.auto import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lora_generator.dataset import StyleLoRADataset, collate_fn
from lora_generator.model import (
    LoRAGenerator,
    encode_rgb_to_scaled_latents,
    load_sdxl_vae,
)


# ═══════════════════════════════════════════════════════════════════════════════
# LoRA ↔ UNet helpers
# ═══════════════════════════════════════════════════════════════════════════════

def lora_key_to_module_path(key: str) -> str:
    """
    'unet.up_blocks.0.attentions.1...to_q.lora.down.weight'
    → 'up_blocks.0.attentions.1...to_q'
    """
    path = key.removeprefix("unet.")
    for suffix in (".lora.down.weight", ".lora.up.weight"):
        if path.endswith(suffix):
            return path[: -len(suffix)]
    raise ValueError(f"Unrecognised LoRA key format: {key!r}")


def build_module_map(keys: list[str]) -> dict[str, tuple[str, str]]:
    """
    Returns {module_path: (down_key, up_key)} for each LoRA-patched Linear.
    """
    modules: dict[str, dict[str, str]] = {}
    for k in keys:
        path = lora_key_to_module_path(k)
        modules.setdefault(path, {})
        if k.endswith(".lora.down.weight"):
            modules[path]["down"] = k
        else:
            modules[path]["up"] = k
    return {p: (v["down"], v["up"]) for p, v in modules.items()}


@contextmanager
def apply_lora_hooks(
    unet,
    lora_dict: dict[str, torch.Tensor],
    scale: float = 1.0,
):
    """
    Temporarily patches UNet Linear layers with LoRA deltas via forward hooks.
    Gradients flow back through the delta into lora_dict values.

    lora_dict values (per-sample, no batch dim):
        down key → [rank, in_features]
        up   key → [out_features, rank]
    """
    handles = []
    module_map = build_module_map(list(lora_dict.keys()))

    for module_path, (down_key, up_key) in module_map.items():
        try:
            linear = unet.get_submodule(module_path)
        except AttributeError:
            continue

        lora_A = lora_dict[down_key]   # [rank, in_features]
        lora_B = lora_dict[up_key]     # [out_features, rank]

        def _make_hook(A: torch.Tensor, B: torch.Tensor, s: float):
            def hook(module, inp, out):
                # Compute the LoRA delta in the same dtype as the UNet output
                # (usually fp16/bf16) to keep memory low and avoid dtype
                # mismatches in matmuls.
                compute_dtype = out.dtype

                x = inp[0].to(compute_dtype)      # [..., in_features]
                A_cast = A.to(compute_dtype)      # [rank, in_features]
                B_cast = B.to(compute_dtype)      # [out_features, rank]

                delta = (x @ A_cast.t()) @ B_cast.t() * s   # [..., out_features]
                return out + delta
            return hook

        h = linear.register_forward_hook(_make_hook(lora_A, lora_B, scale))
        handles.append(h)

    try:
        yield
    finally:
        for h in handles:
            h.remove()


# ═══════════════════════════════════════════════════════════════════════════════
# SDXL single-step helpers
# ═══════════════════════════════════════════════════════════════════════════════

def encode_prompt_sdxl(
    pipeline: StableDiffusionXLPipeline,
    prompt: str,
    device: torch.device,
    do_classifier_free_guidance: bool = True,
) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Returns (prompt_embeds, pooled_prompt_embeds).
    If do_classifier_free_guidance: [2, S, 2048] and [2, 1280] (uncond then cond).
    Else: [1, S, 2048] and [1, 1280].
    """
    prompt_embeds, neg_embeds, pooled, neg_pooled = pipeline.encode_prompt(
        prompt=prompt,
        device=device,
        num_images_per_prompt=1,
        do_classifier_free_guidance=do_classifier_free_guidance,
        negative_prompt="" if do_classifier_free_guidance else None,
    )
    if do_classifier_free_guidance:
        # Concat [uncond, cond] for UNet (first half uncond, second cond)
        prompt_embeds = torch.cat([neg_embeds, prompt_embeds], dim=0)
        pooled = torch.cat([neg_pooled, pooled], dim=0)
    return prompt_embeds, pooled


def make_time_ids(
    device: torch.device,
    dtype: torch.dtype,
    height: int = 512,
    width: int = 512,
) -> torch.Tensor:
    ids = [height, width, 0, 0, height, width]
    return torch.tensor([ids], dtype=dtype, device=device)


def sdxl_latent_from_steps(
    unet,
    scheduler,
    latent: torch.Tensor,
    prompt_embeds: torch.Tensor,
    pooled_embeds: torch.Tensor,
    time_ids: torch.Tensor,
    num_inference_steps: int,
    lora_dict: Optional[dict[str, torch.Tensor]] = None,
    lora_scale: float = 1.0,
    guidance_scale: float = 7.5,
    fixed_timestep: Optional[torch.Tensor] = None,
    no_grad: bool = False,
) -> torch.Tensor:
    """
    Unified sampler for CLIP loss. Uses scale_model_input and optional CFG to match
    the SDXL pipeline so that even GT LoRA produces correct-looking images.
    """
    use_cfg = guidance_scale > 1.0 and prompt_embeds.shape[0] == 2
    if use_cfg:
        # time_ids must be [2, 6] for CFG
        if time_ids.shape[0] == 1:
            time_ids = time_ids.repeat(2, 1)
        added_cond = {"text_embeds": pooled_embeds, "time_ids": time_ids}
    else:
        added_cond = {"text_embeds": pooled_embeds, "time_ids": time_ids}

    def _merge_cfg(noise_pred: torch.Tensor) -> torch.Tensor:
        if not use_cfg:
            return noise_pred
        uncond, cond = noise_pred.chunk(2, dim=0)
        return uncond + guidance_scale * (cond - uncond)

    def _forward():
        if num_inference_steps == 1:
            if fixed_timestep is not None:
                t = fixed_timestep
            else:
                t = torch.randint(200, 800, (1,), device=latent.device)

            latent_in = latent
            if use_cfg:
                latent_in = torch.cat([latent_in, latent_in], dim=0)
            latent_in = scheduler.scale_model_input(latent_in, t)

            cm = apply_lora_hooks(unet, lora_dict, lora_scale) if lora_dict else _null_cm()
            with cm:
                noise_pred = unet(
                    sample=latent_in,
                    timestep=t,
                    encoder_hidden_states=prompt_embeds,
                    added_cond_kwargs=added_cond,
                ).sample
            noise_pred = _merge_cfg(noise_pred)

            alpha_bar = scheduler.alphas_cumprod[t.long().cpu()].to(latent.device, latent.dtype)
            x0 = (latent - (1 - alpha_bar).sqrt() * noise_pred) / alpha_bar.sqrt()
            return x0.clamp(-1, 1)

        scheduler.set_timesteps(num_inference_steps, device=latent.device)
        latents = latent * scheduler.init_noise_sigma

        for t in scheduler.timesteps:
            latent_in = torch.cat([latents, latents], dim=0) if use_cfg else latents
            latent_in = scheduler.scale_model_input(latent_in, t)

            cm = apply_lora_hooks(unet, lora_dict, lora_scale) if lora_dict else _null_cm()
            with cm:
                noise_pred = unet(
                    sample=latent_in,
                    timestep=t,
                    encoder_hidden_states=prompt_embeds,
                    added_cond_kwargs=added_cond,
                ).sample
            noise_pred = _merge_cfg(noise_pred)
            step_out = scheduler.step(noise_pred, t, latents)
            latents = step_out.prev_sample

        return latents

    if no_grad:
        with torch.no_grad():
            return _forward()
    return _forward()


@contextmanager
def _null_cm():
    yield


def _check_nan_inf(tensor: torch.Tensor, name: str, epoch: int, batch_idx: int, sample_i: int) -> bool:
    """Return True if tensor has nan/inf; print one-line debug and stats (min/max/mean)."""
    if not torch.isfinite(tensor).all():
        stats = f"min={tensor.min().item():.6f} max={tensor.max().item():.6f} mean={tensor.float().mean().item():.6f}"
        n_nan = torch.isnan(tensor).sum().item()
        n_inf = torch.isinf(tensor).sum().item()
        print(f"[DEBUG NaN] epoch={epoch} batch_idx={batch_idx} sample_i={sample_i} | {name} | nan_count={n_nan} inf_count={n_inf} | {stats}")
        return True
    return False


# ═══════════════════════════════════════════════════════════════════════════════
# CLIP image encoding
# ═══════════════════════════════════════════════════════════════════════════════

def clip_encode_x0(
    vae: AutoencoderKL,
    clip: CLIPVisionModel,
    x0_latent: torch.Tensor,
    no_grad: bool = False,
) -> torch.Tensor:
    """
    VAE-decode a latent, normalise to [0,1], resize to 224, then CLIP-encode.

    x0_latent : [1, 4, H/8, W/8]
    returns   : [1, clip_hidden]  (pooler_output / CLS embedding)
    """
    def _compute():
        # Match latent dtype/device to the VAE to avoid dtype/device mismatches,
        # especially when the VAE is loaded in fp16.
        latent = x0_latent.to(dtype=vae.dtype, device=vae.device)
        decoded = vae.decode(latent / vae.config.scaling_factor).sample  # [1,3,H,W] in [-1,1]
        img_01 = (decoded.float().clamp(-1, 1) + 1) / 2
        img_224 = F.interpolate(img_01, size=(224, 224), mode="bilinear", align_corners=False)
        return clip(pixel_values=img_224).pooler_output  # [1, D]

    if no_grad:
        with torch.no_grad():
            return _compute()
    return _compute()


def save_latent_as_image(
    vae: AutoencoderKL,
    x0_latent: torch.Tensor,
    path: Path,
) -> None:
    """Decode a single x0 latent [1, 4, H, W] to [0,1] image and save to path."""
    with torch.no_grad():
        latent = x0_latent.to(dtype=vae.dtype, device=vae.device)
        decoded = vae.decode(latent / vae.config.scaling_factor).sample
        img_01 = (decoded.float().clamp(-1, 1) + 1) / 2
    # img_01: [1, 3, H, W], [0, 1]
    save_image(img_01.cpu(), str(path))


# ═══════════════════════════════════════════════════════════════════════════════
# Argument parsing
# ═══════════════════════════════════════════════════════════════════════════════

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train LoRAGenerator")

    # Data
    p.add_argument("--checkpoint_dir", type=str,
                   default="/scratch/ohitit20/checkpoints/blora_universal_style_token")
    p.add_argument("--image_dir", type=str,
                   default="/home/ohitit20/ip-lora/ref_images/style")

    # Models
    p.add_argument("--sdxl_model_id", type=str,
                   default="stabilityai/stable-diffusion-xl-base-1.0")
    p.add_argument(
        "--pretrained_vae_model_name_or_path",
        type=str,
        default=None,
        help=(
            "Same as train_dreambooth_b-lora_sdxl.py: load this VAE instead of "
            "sdxl_model_id's subfolder vae/. If unset, see --vae_model_id."
        ),
    )
    p.add_argument(
        "--vae_model_id",
        type=str,
        default=None,
        help=(
            "Optional standalone VAE id/path (e.g. madebyollin/sdxl-vae-fp16-fix). "
            "Used if --pretrained_vae_model_name_or_path is unset. "
            "If both are unset, loads vae/ from --sdxl_model_id (B-LoRA default)."
        ),
    )
    p.add_argument("--clip_model_id", type=str,
                   default="openai/clip-vit-large-patch14")

    # LoRA generator: CLIP pixels vs SDXL VAE latents (B-LoRA preprocessing)
    p.add_argument(
        "--style_encoder",
        type=str,
        choices=("clip", "vae_latents"),
        default="vae_latents",
        help="What conditions the generator: CLIP image tokens or VAE-scaled latents.",
    )
    p.add_argument(
        "--latent_patch_size",
        type=int,
        default=4,
        help="Conv patch stride for vae_latents memory (latent h,w must be divisible).",
    )

    # LoRA generator architecture
    p.add_argument("--d_model", type=int, default=512)
    p.add_argument("--n_layers", type=int, default=4)
    p.add_argument("--n_heads", type=int, default=8)

    # Optimisation
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--weight_decay", type=float, default=1e-4)
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--batch_size", type=int, default=4)

    # Loss weights
    p.add_argument("--lambda_clip", type=float, default=1.0,
                   help="Weight of CLIP image loss. 0 disables it entirely.")
    p.add_argument("--clip_loss_warmup_epochs", type=int, default=5,
                   help="Epochs to train with weight MSE only before enabling CLIP loss.")
    p.add_argument("--clip_ramp_epochs", type=int, default=10,
                   help="Epochs to linearly ramp lambda_clip from 0 to full value after warmup.")
    p.add_argument(
        "--num_inference_steps",
        type=int,
        default=1,
        help=(
            "Number of DDIM steps used in the CLIP image loss sampler. "
            "Set to 1 to use the original single-step x0 estimator, or e.g. 50 "
            "for a full sampler. This is the single hyperparameter to change "
            "to switch between 1-step and multi-step behaviour."
        ),
    )

    # Image generation
    p.add_argument("--generation_prompt", type=str, default="a photo")
    p.add_argument("--generation_height", type=int, default=512)
    p.add_argument("--generation_width", type=int, default=512)
    p.add_argument("--lora_scale", type=float, default=1.0)
    p.add_argument("--guidance_scale", type=float, default=7.5,
                   help="Classifier-free guidance scale for SDXL generation (match pipeline default).")
    p.add_argument("--sdxl_timestep", type=int, default=None,
                   help="Fixed SDXL timestep for the single denoising step. "
                        "Random in [200, 800] if not set.")

    # Output
    p.add_argument("--output_dir", type=str,
                   default="/scratch/ohitit20/checkpoints/lora_generator")
    p.add_argument("--save_every", type=int, default=10)
    p.add_argument("--save_training_images", action="store_true",
                   help="Save SDXL-generated images (gen vs gt) to output_dir/training_samples/.")
    p.add_argument("--save_training_images_every", type=int, default=1,
                   help="Save training images every N epochs (when --save_training_images).")

    # W&B
    p.add_argument("--wandb", action="store_true")
    p.add_argument("--wandb_project", type=str, default="lora-generator")
    p.add_argument("--wandb_run_name", type=str, default=None)

    return p.parse_args()


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    args = parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    os.makedirs(args.output_dir, exist_ok=True)

    if args.wandb:
        import wandb
        wandb.init(
            project=args.wandb_project,
            name=args.wandb_run_name,
            config=vars(args),
        )

    # ── Dataset ──────────────────────────────────────────────────────────────
    vae_hw = (
        (args.generation_height, args.generation_width)
        if args.style_encoder == "vae_latents"
        else None
    )
    dataset = StyleLoRADataset(
        checkpoint_dir=args.checkpoint_dir,
        image_dir=args.image_dir,
        clip_model_id=args.clip_model_id,
        cache_loras=True,
        vae_image_size=vae_hw,
    )
    print(f"Dataset: {len(dataset)} styles → {dataset.styles}")

    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        drop_last=False,
    )

    # ── LoRA Generator ───────────────────────────────────────────────────────
    sample = dataset[0]
    model = LoRAGenerator.from_sample_lora(
        sample_lora_dict=sample["lora_dict"],
        d_model=args.d_model,
        n_layers=args.n_layers,
        n_heads=args.n_heads,
        clip_model=args.clip_model_id,
        style_encoder=args.style_encoder,
        latent_patch_size=args.latent_patch_size,
    ).to(device)

    trainable_params = [p for p in model.parameters() if p.requires_grad]
    n_trainable = sum(p.numel() for p in trainable_params)
    print(f"LoRAGenerator trainable parameters: {n_trainable:,}")

    optimizer = torch.optim.AdamW(
        trainable_params, lr=args.lr, weight_decay=args.weight_decay
    )

    # ── SDXL + VAE + CLIP for image-space loss ───────────────────────────────
    sdxl_unet = None
    vae = None
    clip_for_loss = None
    scheduler = None
    prompt_embeds = None
    pooled_embeds = None
    time_ids = None
    latent_h = latent_w = None

    vae_override = args.pretrained_vae_model_name_or_path or args.vae_model_id
    need_vae = args.style_encoder == "vae_latents" or args.lambda_clip > 0
    if need_vae:
        print("Loading SDXL VAE (B-LoRA script convention: base subfolder or override) …")
        vae = load_sdxl_vae(
            args.sdxl_model_id,
            pretrained_vae_model_name_or_path=vae_override if vae_override else None,
            torch_dtype=torch.float32,
        ).to(device)
        vae.requires_grad_(False)

    if args.lambda_clip > 0:
        print("Loading SDXL for CLIP image loss …")
        if vae is None:
            raise RuntimeError("CLIP loss requires a VAE; this should not happen.")

        sdxl_pipe = StableDiffusionXLPipeline.from_pretrained(
            args.sdxl_model_id,
            vae=vae,
            torch_dtype=torch.float16,
        ).to(device)
        sdxl_unet = sdxl_pipe.unet
        sdxl_unet.requires_grad_(False)
        sdxl_pipe.text_encoder.requires_grad_(False)
        sdxl_pipe.text_encoder_2.requires_grad_(False)

        with torch.no_grad():
            prompt_embeds, pooled_embeds = encode_prompt_sdxl(
                sdxl_pipe,
                args.generation_prompt,
                device,
                do_classifier_free_guidance=(getattr(args, "guidance_scale", 7.5) > 1.0),
            )

        time_ids = make_time_ids(
            device, torch.float16,
            height=args.generation_height,
            width=args.generation_width,
        )

        # Use same scheduler as B-LoRA validation (DPMSolverMultistepScheduler) so
        # generation matches how B-LoRA checkpoints are meant to be used (see
        # train_dreambooth_b-lora_sdxl.py validation path).
        scheduler_config = sdxl_pipe.scheduler.config
        scheduler_args = {}
        variance_type = getattr(
            scheduler_config, "variance_type",
            scheduler_config.get("variance_type") if isinstance(scheduler_config, dict) else None,
        )
        if variance_type in ["learned", "learned_range"]:
            scheduler_args["variance_type"] = "fixed_small"
        scheduler = DPMSolverMultistepScheduler.from_config(
            scheduler_config, **scheduler_args
        )

        clip_for_loss = CLIPVisionModel.from_pretrained(args.clip_model_id).to(device)
        clip_for_loss.requires_grad_(False)

        latent_h = args.generation_height // 8
        latent_w = args.generation_width  // 8

        # Free pipeline object (keep unet, vae)
        del sdxl_pipe
        torch.cuda.empty_cache()

        if args.save_training_images:
            (Path(args.output_dir) / "training_samples").mkdir(parents=True, exist_ok=True)

    # ── Training loop ────────────────────────────────────────────────────────
    for epoch in range(1, args.epochs + 1):
        model.train()
        sum_loss_w = 0.0
        sum_loss_c = 0.0
        n_steps = 0
        use_clip = (
            args.lambda_clip > 0
            and sdxl_unet is not None
            and epoch > args.clip_loss_warmup_epochs
        )
        # Linear ramp: after warmup, scale lambda_clip from 0 to full over clip_ramp_epochs
        if use_clip:
            epochs_since_warmup = epoch - args.clip_loss_warmup_epochs
            ramp = min(1.0, epochs_since_warmup / args.clip_ramp_epochs)
            effective_lambda_clip = args.lambda_clip * ramp
        else:
            effective_lambda_clip = 0.0

        # Progress bar over training batches for this epoch
        batch_idx = 0
        for batch in tqdm(loader, desc=f"Epoch {epoch}/{args.epochs}", leave=False):
            pixel_values = batch["pixel_values"].to(device)
            lora_batch = {k: v.to(device) for k, v in batch["lora_dict"].items()}
            B = pixel_values.shape[0]

            optimizer.zero_grad()

            # ── Forward ────────────────────────────────────────────────
            if args.style_encoder == "vae_latents":
                if vae is None:
                    raise RuntimeError("style_encoder=vae_latents requires VAE loading.")
                vp = batch["vae_pixel_values"].to(device=device, dtype=vae.dtype)
                with torch.no_grad():
                    lat = encode_rgb_to_scaled_latents(vae, vp, sample=True)
                generated_lora = model(scaled_latents=lat.float())
            else:
                generated_lora = model(pixel_values=pixel_values)

            # ── Loss 1: weight MSE ─────────────────────────────────────
            loss_w = sum(
                F.mse_loss(generated_lora[k], lora_batch[k].float())
                for k in generated_lora
            ) / len(generated_lora)

            # ── Loss 2: CLIP image MSE ─────────────────────────────────
            loss_c = torch.zeros(1, device=device)

            if use_clip:
                per_sample_clip = []

                for i in range(B):
                    # Unbatch: per-sample LoRA dicts
                    gen_lora_i = {k: v[i] for k, v in generated_lora.items()}
                    gt_lora_i  = {k: v[i].float() for k, v in lora_batch.items()}

                    # Same starting noise for both (ensures comparable images)
                    z = torch.randn(
                        1, 4, latent_h, latent_w,
                        device=device, dtype=torch.float16,
                    )

                    half = {"dtype": torch.float16}

                    # Run num_inference_steps of DDIM for each path; then one backward
                    # of the cosine loss flows through the entire chain (all steps) to
                    # the generator — we do not backprop per-step, only once per sample.
                    fixed_t = (
                        torch.tensor([args.sdxl_timestep], device=device)
                        if args.sdxl_timestep is not None
                        else None
                    )

                    x0_gen = sdxl_latent_from_steps(
                        unet=sdxl_unet,
                        scheduler=scheduler,
                        latent=z,
                        prompt_embeds=prompt_embeds.to(**half),
                        pooled_embeds=pooled_embeds.to(**half),
                        time_ids=time_ids,
                        num_inference_steps=args.num_inference_steps,
                        lora_dict={k: v.to(**half) for k, v in gen_lora_i.items()},
                        lora_scale=args.lora_scale,
                        guidance_scale=args.guidance_scale,
                        fixed_timestep=fixed_t,
                        no_grad=False,
                    )
                    if _check_nan_inf(x0_gen.float(), "x0_gen", epoch, batch_idx, i):
                        continue  # skip this sample for loss to avoid backprop through nan

                    # GT path: load LoRA into UNet like B-LoRA inference (no hooks)
                    gt_lora_device = next(iter(gt_lora_i.values())).device
                    LoraLoaderMixin.load_lora_into_unet(
                        {k: v.to(**half) for k, v in gt_lora_i.items()},
                        None,
                        sdxl_unet,
                    )
                    try:
                        x0_gt = sdxl_latent_from_steps(
                            unet=sdxl_unet,
                            scheduler=scheduler,
                            latent=z,
                            prompt_embeds=prompt_embeds.to(**half),
                            pooled_embeds=pooled_embeds.to(**half),
                            time_ids=time_ids,
                            num_inference_steps=args.num_inference_steps,
                            lora_dict=None,
                            lora_scale=args.lora_scale,
                            guidance_scale=args.guidance_scale,
                            fixed_timestep=fixed_t,
                            no_grad=True,
                        )
                    finally:
                        # Clear loaded LoRA so next sample's gen path doesn't see GT LoRA
                        zero_lora = {
                            k: torch.zeros_like(v, device=gt_lora_device, dtype=v.dtype)
                            for k, v in gt_lora_i.items()
                        }
                        LoraLoaderMixin.load_lora_into_unet(zero_lora, None, sdxl_unet)

                    if _check_nan_inf(x0_gt.float(), "x0_gt", epoch, batch_idx, i):
                        continue

                    # Optionally save gen vs gt images (first sample of first batch, every N epochs)
                    if (
                        args.save_training_images
                        and (epoch % args.save_training_images_every == 0)
                        and batch_idx == 0
                        and i == 0
                    ):
                        save_dir = Path(args.output_dir) / "training_samples"
                        style_name = batch["style_names"][i]
                        save_latent_as_image(
                            vae, x0_gen.detach().float(), save_dir / f"epoch_{epoch:04d}_{style_name}_gen.png"
                        )
                        save_latent_as_image(
                            vae, x0_gt.float(), save_dir / f"epoch_{epoch:04d}_{style_name}_gt.png"
                        )

                    # CLIP embeddings — VAE decode + CLIP encode
                    # Gradients flow through generated path only
                    clip_gen = clip_encode_x0(vae, clip_for_loss, x0_gen.float(), no_grad=False)
                    if _check_nan_inf(clip_gen, "clip_gen", epoch, batch_idx, i):
                        continue

                    clip_gt  = clip_encode_x0(vae, clip_for_loss, x0_gt.float(),  no_grad=True)
                    if _check_nan_inf(clip_gt, "clip_gt", epoch, batch_idx, i):
                        continue

                    # Cosine similarity loss: 1 - cos(clip_gen, clip_gt)
                    gen_norm = F.normalize(clip_gen, p=2, dim=-1)
                    gt_norm  = F.normalize(clip_gt.detach(), p=2, dim=-1)
                    cos_sim  = (gen_norm * gt_norm).sum(dim=-1)  # [batch_dim]
                    sample_loss = 1.0 - cos_sim.mean()
                    if _check_nan_inf(sample_loss.unsqueeze(0), "cos_loss", epoch, batch_idx, i):
                        continue

                    per_sample_clip.append(sample_loss)

                if len(per_sample_clip) > 0:
                    loss_c = torch.stack(per_sample_clip).mean()
                # else: loss_c stays 0 (no valid CLIP samples this batch)

            # ── Optimise ───────────────────────────────────────────────
            total_loss = loss_w + effective_lambda_clip * loss_c
            if not torch.isfinite(total_loss).all():
                print(f"[DEBUG NaN] epoch={epoch} batch_idx={batch_idx} | total_loss nan/inf (loss_w={loss_w.item():.6f} loss_c={loss_c.item():.6f})")
            total_loss.backward()
            torch.nn.utils.clip_grad_norm_(trainable_params, max_norm=1.0)
            optimizer.step()

            sum_loss_w += loss_w.item()
            sum_loss_c += loss_c.item()
            n_steps += 1
            batch_idx += 1

        # ── Logging ────────────────────────────────────────────────────
        avg_w = sum_loss_w / n_steps
        avg_c = sum_loss_c / n_steps
        avg_total = avg_w + effective_lambda_clip * avg_c
        print(
            f"[{epoch:04d}/{args.epochs}]  "
            f"loss_weight={avg_w:.6f}  "
            f"loss_clip={avg_c:.6f}  "
            f"total={avg_total:.6f}"
        )

        if args.wandb:
            import wandb
            wandb.log({
                "epoch": epoch,
                "loss/weight_mse": avg_w,
                "loss/clip_image": avg_c,
                "loss/total": avg_total,
            })

        # ── Checkpoint ─────────────────────────────────────────────────
        if epoch % args.save_every == 0 or epoch == args.epochs:
            save_path = Path(args.output_dir) / f"checkpoint_epoch{epoch:04d}.pt"
            torch.save(
                {
                    "epoch": epoch,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "args": vars(args),
                    "keys": model.keys,
                    "key_shapes": model.key_shapes,
                },
                save_path,
            )
            print(f"  → Saved {save_path}")

    if args.wandb:
        import wandb
        wandb.finish()


if __name__ == "__main__":
    main()
